export const CURRENT_USER_ID = "jonathan";

export const ROBOT_COLUMNS = [
  { id: "todo", name: "To Do" },
  { id: "progress", name: "In Progress" },
  { id: "testing", name: "Testing" },
  { id: "done", name: "Done" },
];

export const EMPTY_COLUMNS = [
  { id: "todo", name: "To Do" },
  { id: "progress", name: "In Progress" },
  { id: "testing", name: "Testing" },
  { id: "done", name: "Done" },
];

export const members = [
  { id: "robert", name: "Robert W", role: "Hardware & firmware", hue: 200 },
  { id: "marin", name: "Marin Y", role: "Navigation & vision", hue: 160 },
  { id: "jonathan", name: "Jonathan Y", role: "Field & safety", hue: 22 },
];

export const labels = [
  { id: "vision", name: "Vision", color: "#4a7388" },
  { id: "hardware", name: "Hardware", color: "#8a7354" },
  { id: "firmware", name: "Firmware", color: "#4d7a72" },
  { id: "field", name: "Field Test", color: "#9a6b45" },
  { id: "safety", name: "Safety", color: "#b45c4a" },
  { id: "nav", name: "Navigation", color: "#4d6d8a" },
  { id: "power", name: "Power", color: "#8a6844" },
  { id: "design", name: "Design", color: "#7a6a58" },
  { id: "comms", name: "Comms", color: "#5a7a74" },
];

export const PROJECT_ICONS = ["walker", "rover", "swarm", "arm", "sat", "chip"];

export const PROJECT_COLORS = ["#3d9ec4", "#4f9e96", "#c4a46a", "#e07a5f", "#7b8cde", "#d0894a"];

function cols() {
  return ROBOT_COLUMNS.map((c) => ({ ...c, id: c.id }));
}

export const projects = [
  {
    id: "orion",
    name: "Orion Walker",
    description: "Humanoid walking-prototype til lager og let feltarbejde.",
    color: "#4a7388",
    icon: "walker",
    columns: cols(),
  },
  {
    id: "luna",
    name: "Luna Rover Mk II",
    description: "Planetrover med stereo vision, LiDAR og 6-hjulet rocker-bogie.",
    color: "#8a7354",
    icon: "rover",
    columns: cols(),
  },
  {
    id: "hive",
    name: "Hive Swarm",
    description: "Decentral sværm til lagerinspektion og søgning.",
    color: "#4d7a72",
    icon: "swarm",
    columns: cols(),
  },
];

export const tasks = [
  /* ——— Orion Walker ——— */
  {
    id: "o1",
    projectId: "orion",
    columnId: "todo",
    title: "Evaluer aktuator-leverandør til ankler",
    description: "Sammenlign tre quasi-direct-drive enheder. Moment, vægt og leveringstid.",
    labels: ["hardware"],
    priority: "medium",
    assigneeId: "robert",
    due: "2026-10-02",
    order: 0,
  },
  {
    id: "o2",
    projectId: "orion",
    columnId: "todo",
    title: "Kortlæg kabeltræk i torso",
    description: "Undgå klem ved 40° rotation. Dokumentér i CAD-lag.",
    labels: ["hardware", "design"],
    priority: "low",
    assigneeId: "robert",
    due: null,
    order: 1,
  },
  {
    id: "o3",
    projectId: "orion",
    columnId: "testing",
    title: "Battery thermal test i 40°C",
    description: "Kør 90 minutters gangcyklus i klimakammer. Log cellespænding og hudtemperatur.",
    labels: ["power", "safety"],
    priority: "high",
    assigneeId: "robert",
    due: "2026-09-18",
    order: 0,
    progress: 35,
  },
  {
    id: "o4",
    projectId: "orion",
    columnId: "todo",
    title: "On-device SLAM vs. docket kort",
    description: "Hvad kan Jetson bære uden at droppe 50 Hz kontrol-loop?",
    labels: ["nav", "vision"],
    priority: "medium",
    assigneeId: "marin",
    due: "2026-09-25",
    order: 1,
  },
  {
    id: "o5",
    projectId: "orion",
    columnId: "todo",
    title: "Design chassis til humanoid proto v2",
    description: "Lettere hofteplade i aluminium. Behold samme bolt-mønster som v1.",
    labels: ["design", "hardware"],
    priority: "high",
    assigneeId: "robert",
    due: "2026-09-22",
    order: 0,
  },
  {
    id: "o6",
    projectId: "orion",
    columnId: "todo",
    title: "Håndled med 7 DOF — envelope",
    description: "Rækkevidde til hylde i 1,8 m. Undgå singularity i naturligt greb.",
    labels: ["design"],
    priority: "medium",
    assigneeId: "marin",
    due: "2026-10-06",
    order: 1,
  },
  {
    id: "o7",
    projectId: "orion",
    columnId: "progress",
    title: "Kalibrer stereo vision på hovedenhed",
    description: "Checkerboard i 0,6 / 1,2 / 2,4 m. Gem extrinsics i robot-kalibreringsfil.",
    labels: ["vision"],
    priority: "high",
    assigneeId: "marin",
    due: "2026-09-14",
    order: 0,
  },
  {
    id: "o8",
    projectId: "orion",
    columnId: "progress",
    title: "Test gripper-torque på Arm Unit 4",
    description: "Løft 1,5 kg kasse 200 gange. Se efter backlash og varme i gear.",
    labels: ["hardware", "field"],
    priority: "medium",
    assigneeId: "jonathan",
    due: "2026-09-16",
    order: 1,
  },
  {
    id: "o9",
    projectId: "orion",
    columnId: "progress",
    title: "Integrer LiDAR i navigation stack",
    description: "Mid-360 som lag-1 obstacle. Fusionér med stereo til nærzone.",
    labels: ["nav", "vision"],
    priority: "high",
    assigneeId: "marin",
    due: "2026-09-19",
    order: 2,
  },
  {
    id: "o10",
    projectId: "orion",
    columnId: "testing",
    title: "Obstacle avoidance i warehouse demo",
    description: "Paller, personer og en løbende pallejack. Ingen e-stop i 20 minutter.",
    labels: ["nav", "field", "safety"],
    priority: "urgent",
    assigneeId: "jonathan",
    due: "2026-09-12",
    order: 0,
    progress: 70,
  },
  {
    id: "o11",
    projectId: "orion",
    columnId: "testing",
    title: "Safety interlock review",
    description: "Gennemgå e-stop, led-låg og software-watchdog med safety-lead.",
    labels: ["safety"],
    priority: "urgent",
    assigneeId: "jonathan",
    due: "2026-09-11",
    order: 1,
    progress: 50,
  },
  {
    id: "o12",
    projectId: "orion",
    columnId: "done",
    title: "Felt-demo hos lagerpartner",
    description: "To walkers, én operatør. Medbring reservedelssæt og log-kabel.",
    labels: ["field"],
    priority: "high",
    assigneeId: "jonathan",
    due: "2026-09-28",
    order: 0,
  },
  {
    id: "o13",
    projectId: "orion",
    columnId: "done",
    title: "Valg af IMU — Bosch BMI088",
    description: "Vandt over to alternativer på støj og levering.",
    labels: ["hardware"],
    priority: "medium",
    assigneeId: "robert",
    due: "2026-08-28",
    order: 0,
  },
  {
    id: "o14",
    projectId: "orion",
    columnId: "done",
    title: "Første stand-up fra hug",
    description: "Stabilt på 4 forsøg. Video i lab-arkiv.",
    labels: ["firmware"],
    priority: "high",
    assigneeId: "marin",
    due: "2026-09-02",
    order: 1,
  },

  /* ——— Luna Rover Mk II ——— */
  {
    id: "l1",
    projectId: "luna",
    columnId: "todo",
    title: "Støv-tætning af hjulnav",
    description: "Simuleret regolith. Labyrinth seal vs. felt.",
    labels: ["hardware"],
    priority: "medium",
    assigneeId: "robert",
    due: "2026-10-10",
    order: 0,
  },
  {
    id: "l2",
    projectId: "luna",
    columnId: "todo",
    title: "Stereo + LiDAR fusion på lavt lys",
    description: "Test i mørkt hangar med kun LED-mast.",
    labels: ["vision", "nav"],
    priority: "high",
    assigneeId: "marin",
    due: "2026-09-21",
    order: 0,
  },
  {
    id: "l3",
    projectId: "luna",
    columnId: "todo",
    title: "Rocker-bogie ophæng v3",
    description: "Hæv ground clearance 30 mm uden at flytte CoG.",
    labels: ["design", "hardware"],
    priority: "medium",
    assigneeId: "robert",
    due: "2026-09-30",
    order: 0,
  },
  {
    id: "l4",
    projectId: "luna",
    columnId: "progress",
    title: "Autonom navigation over løst grus",
    description: "GPS-denied. Rent visuelt odometri + IMU.",
    labels: ["nav", "field"],
    priority: "high",
    assigneeId: "marin",
    due: "2026-09-17",
    order: 0,
  },
  {
    id: "l5",
    projectId: "luna",
    columnId: "testing",
    title: "Battery thermal test i 40°C",
    description: "Samme protokol som Orion, men med sol-simulator.",
    labels: ["power", "safety"],
    priority: "high",
    assigneeId: "robert",
    due: "2026-09-15",
    order: 0,
    progress: 20,
  },
  {
    id: "l6",
    projectId: "luna",
    columnId: "done",
    title: "Mast-kamera 2K stream",
    description: "Stabil 15 fps over mesh-radio.",
    labels: ["comms", "vision"],
    priority: "low",
    assigneeId: "robert",
    due: "2026-09-01",
    order: 0,
  },

  /* ——— Hive Swarm ——— */
  {
    id: "h1",
    projectId: "hive",
    columnId: "todo",
    title: "Swarm communication protocol",
    description: "Gossip + heartbeat. Max 80 ms latency i 12-node test.",
    labels: ["comms", "firmware"],
    priority: "high",
    assigneeId: "robert",
    due: "2026-09-24",
    order: 0,
  },
  {
    id: "h2",
    projectId: "hive",
    columnId: "todo",
    title: "Kollision uden central planner",
    description: "Local ORCA vs. potential fields i gang. Vælg én.",
    labels: ["nav"],
    priority: "medium",
    assigneeId: "marin",
    due: "2026-09-20",
    order: 0,
  },
  {
    id: "h3",
    projectId: "hive",
    columnId: "progress",
    title: "Docking og trådløs opladning",
    description: "Fire pads, automatisk land. Fejl under 8 mm.",
    labels: ["hardware", "power"],
    priority: "medium",
    assigneeId: "robert",
    due: "2026-09-26",
    order: 0,
  },
  {
    id: "h4",
    projectId: "hive",
    columnId: "testing",
    title: "Søgemønster i lagerhal",
    description: "12 enheder, 400 m², find tre mærkede kasser.",
    labels: ["field", "nav"],
    priority: "high",
    assigneeId: "jonathan",
    due: "2026-09-13",
    order: 0,
    progress: 40,
  },
  {
    id: "h5",
    projectId: "hive",
    columnId: "done",
    title: "LED-identitet pr. node",
    description: "Farvekode + blink-mønster synligt på 15 m.",
    labels: ["design", "firmware"],
    priority: "low",
    assigneeId: "jonathan",
    due: "2026-08-20",
    order: 0,
  },
];

export const notifications = [
  { id: "n1", text: "Safety interlock review er sat til i dag.", time: "09:14" },
  { id: "n2", text: "Warehouse-demo mangler 2 dage — Jonathan venter på LiDAR-fix.", time: "I går" },
  { id: "n3", text: "Battery-testprotokol er delt med Luna-teamet.", time: "Tirsdag" },
];

export const SEED = {
  currentProjectId: "all",
  view: "board",
  search: "",
  sidebarOpen: true,
  filter: {
    labels: [],
    priority: null,
    assignee: null,
    due: null,
  },
  projects,
  tasks,
  members,
  labels,
};
